input:
  keyboard_implementation: "glfw"
render:
  implementation: "glfw"
  shader_implementation: "glsl"
resource:
  resource_dir: "C:/Projects/ogle/resources"
window:
  implementation: "glfw"
  width: 1024
  height: 768
  title: "Mesh Viewer"
  opengl_major_version: 4
  opengl_minor_version: 0
  msaa_samples: 4
