/**
 * @file ogle_std.inc
 * @brief Group header for std library.
 *
 * This header customizes foundational parts of C++ and must be included before
 * all others. This is emphasized by naming it "ogle_std.inc"; it isn't
 * self-contained, but must be included in specific places.
 */

#ifndef OGLE_INCLUDES_STD_OGLE_STD_INC_
#define OGLE_INCLUDES_STD_OGLE_STD_INC_

#include "std/containers.h"
#include "std/custom_allocator.h"
#include "std/new_wrappers.h"

#endif  // OGLE_INCLUDES_STD_OGLE_STD_INC_
